### ISSUE TITLE
is quikgrid necessary?

### ISSUE THREAD

**Issue by bmander** [graphserver/graphserver#18]
is quikgrid necessary?

**Comment by bmander** [comment]
nope. removed it. 8af0f67ea5445a72af74b26d81c9de47c1636da5

**Comment by ninowalker** [comment]
This code is very useful for calculating travel-time contours; maybe it should live in another project, or is this functionality implemented elsewhere?

**Comment by bmander** [comment]
It is: it should live in a timeshed application of graphserver, not graphserver itself.
