### ISSUE TITLE
zero-weight edge bug

### ISSUE THREAD

**Issue by bmander** [graphserver/graphserver#26]
http://groups.google.com/group/graphserver/browse_thread/thread/10ae5c4c1ed1c662?hl=en_US

**Comment by dzwarg** [comment]
Fixed in commit:

dzwarg/graphserver@a883b61cd89abd68c12ce3837bb3632c8fe0d8d2

Included in Pull Request 29

**Comment by bmander** [comment]
59f9c48c140bab3faa84cf46b38a101db707af7f
